# bipedal-locomotion-framework requires 10.13 for std::bad_cast_any
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.13                      # [osx and x86_64]

# Pin opencv 4.5.1 to as a workaround for https://github.com/robotology/robotology-superbuild/issues/711
opencv:
  - 4.5.1

# For some reason, the variant of Python in conda-forge-pinning is not considered by conda build/mambabuild on Windows
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
