# bipedal-locomotion-framework requires 10.13 for std::bad_cast_any
# robometry requeries 10.15 for std::filesystem
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.15                      # [osx and x86_64]

qt:
  - 5.15

qt_main:
  - 5.15

# Workaround for:
# * https://github.com/robotology/robotology-superbuild/pull/1574#issuecomment-1898498891
# * https://github.com/robotology/robotology-superbuild/issues/1572#issuecomment-1911740644
swig:
 - 4.1.0
