# bipedal-locomotion-framework requires 10.13 for std::bad_cast_any
# robometry requeries 10.15 for std::filesystem
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.15                      # [osx and x86_64]

qt:
  - 5.15

qt_main:
  - 5.15

cmake:
  - 3.25
